name: xx2
channels:
- conda-forge
- pkgs/main
dependencies:
- gensim
- h5py
- ipython
- jedi
- numpy
- pandas
- pygments
- pysmiles
- python=3.10
- pytorch==2.1
- pytorch-lightning==1.9.5
- scikit-learn
- scipy=1.13.1
- seaborn
- transformers
- pip:
  - deepchem==2.8.0
  - mol2vec==0.2.2
  - omegaconf==2.3.0

