batch_size: 64
bins:
- 0
- 10
checkpoint_path: /root/complex/ckpts/bacteria_morgan_chembert_probert_attention-epoch=7-metric=0.81.ckpt
classify: true
device: 0
drug_featurizer: MorganFeaturizer,ChemBertaFeaturizer
drug_shape: 2048
ensemble_learn: false
experiment_id: bacteria_predict_morgan_chembert_protbert_mhattention
latent_dimension: 1024
loss_type: OR
lr: 0.0001
lr_t0: 10
model_architecture: MorganChemBertaMhAttention
num_classes: 2
num_workers: 4
replicate: 0
shuffle: true
target_featurizer: ProtBertFeaturizer
target_shape: 1024
task: bacteria_predict
